In [38]:
import numpy as np

def cuboid_inertia(w, h, d, m):

    Ixx = (1/12) * m * (h**2 + d**2)
    Iyy = (1/12) * m * (w**2 + d**2)
    Izz = (1/12) * m * (w**2 + h**2)

    I = np.array([
        [Ixx, 0.0, 0.0],
        [0.0, Iyy, 0.0],
        [0.0, 0.0, Izz]
    ])

    return I


def cylinder_inertia(r, h, m):

    Ixx = (1/12) * m * (3*(r**2) + h**2)
    Iyy = Ixx
    Izz = (1/2) * m * (r**2)

    I = np.array([
        [Ixx, 0.0, 0.0],
        [0.0, Iyy, 0.0],
        [0.0, 0.0, Izz]
    ])

    return I


In [39]:
def shift_inertia(I_com, m, r_com):
    """
    Shift inertia tensor from COM to reference point P=(0,0,0)
    using the parallel axis theorem.
    
    r_com = (x, y, z) position of COM relative to P
    """
    r = np.array(r_com)
    d2 = np.dot(r, r)          # |d|^2
    I3 = np.identity(3)

    return I_com + m * (d2 * I3 - np.outer(r, r))

## Motor 1

In [40]:
w1 = 0.045   # meters
h1 = 0.022
d1 = 0.044
m1 = 0.075   # kg

I1 = cuboid_inertia(w1, h1, d1, m1)
print(I1)

[[1.512500e-05 0.000000e+00 0.000000e+00]
 [0.000000e+00 2.475625e-05 0.000000e+00]
 [0.000000e+00 0.000000e+00 1.568125e-05]]


## Razor Connection

In [41]:
r2 = 0.0055
h2 = 0.008
m2 = 0.010

I2 = cylinder_inertia(r2, h2, m2)
print(I2)

[[1.28958333e-07 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.28958333e-07 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.51250000e-07]]


## Motor 2


In [42]:
w3 = 0.053   # meters
h3 = 0.050
d3 = 0.024
m3 = 0.082   # kg

I3 = cuboid_inertia(w3, h3, d3, m3)
print(I3)

[[2.10193333e-05 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.31308333e-05 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.62781667e-05]]


## H Arm

#### H arm Vertical

In [43]:
w4 = 0.002   # meters
h4 = 0.025
d4 = 0.128
m4 = 0.018   # kg

I4 = cuboid_inertia(w4, h4, d4, m4)
print(I4)

[[2.55135e-05 0.00000e+00 0.00000e+00]
 [0.00000e+00 2.45820e-05 0.00000e+00]
 [0.00000e+00 0.00000e+00 9.43500e-07]]


#### H arm Middle

In [44]:
w5 = 0.053   # meters
h5 = 0.025
d5 = 0.004
m5 = 0.018   # kg

I5 = cuboid_inertia(w5, h5, d5, m5)
print(I5)

[[9.6150e-07 0.0000e+00 0.0000e+00]
 [0.0000e+00 4.2375e-06 0.0000e+00]
 [0.0000e+00 0.0000e+00 5.1510e-06]]


#### H Arm

In [51]:
I_shifted_1 = shift_inertia(I4, m4, (-0.0275, 0, -0.052))
I_shifted_2 = shift_inertia(I5, m5, (0, 0, -0.052))
I_shifted_3 = shift_inertia(I4, m4, (0.0275, 0, -0.052))

I_shifted_H = I_shifted_1 + I_shifted_2 + I_shifted_3
print(I_shifted_H)

[[1.980045e-04 0.000000e+00 0.000000e+00]
 [0.000000e+00 2.266425e-04 0.000000e+00]
 [0.000000e+00 0.000000e+00 3.426300e-05]]


## Motor 3

In [46]:
w6 = 0.053   # meters
h6 = 0.025
d6 = 0.060
m6 = 0.085   # kg

I6 = cuboid_inertia(w6, h6, d6, m6)
print(I6)

[[2.99270833e-05 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 4.53970833e-05 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.43241667e-05]]


In [52]:
I_shifted_M3 = shift_inertia(I6, m6, (0, 0, -0.015))
print(I_shifted_M3)

[[4.90520833e-05 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 6.45220833e-05 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.43241667e-05]]


## Rod

In [47]:
r7 = 0.006
h7 = 0.055
m7 = 0.020

I7 = cylinder_inertia(r7, h7, m7)
print(I7)

[[5.22166667e-06 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 5.22166667e-06 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.60000000e-07]]


## Gripper Base

In [48]:
w8 = 0.040   # meters
h8 = 0.003
d8 = 0.050
m8 = 0.020   # kg

I8 = cuboid_inertia(w8, h8, d8, m8)
print(I8)

[[4.18166667e-06 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 6.83333333e-06 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.68166667e-06]]


## Motor 4

In [49]:
w9 = 0.044   # meters
h9 = 0.045
d9 = 0.020
m9 = 0.055   # kg

I9 = cuboid_inertia(w9, h9, d9, m9)
print(I9)

[[1.11145833e-05 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.07066667e-05 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.81545833e-05]]


## Gripper

In [50]:
w10 = 0.010   # meters
h10 = 0.003
d10 = 0.060
m10 = 0.020   # kg

I10 = cuboid_inertia(w10, h10, d10, m10)
print(I10)

[[6.01500000e-06 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 6.16666667e-06 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.81666667e-07]]


In [53]:
I_shifted_G = shift_inertia(I10, m10, (0, 0, -0.022))
print(I_shifted_G)

[[1.56950000e-05 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.58466667e-05 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.81666667e-07]]
